### ISSUE TITLE
Fix grammatical errors in README

### ISSUE THREAD

**Issue by janKozie1** [PawelPerek/eeric-core#3]
ASAP

**Comment by PawelPerek** [comment]
Maybe provide a concrete example..

**Comment by janKozie1** [comment]
e.g.

>Maybe provide concrete example..

should be

>Maybe provide a concrete example..

**Comment by PawelPerek** [comment]
Maybe provide the concrete example..

**Comment by PawelPerek** [comment]
Please finish your repo https://github.com/janKozie1/spelling_corrector before you start unproductively critisizing other people readmes.
